### ISSUE TITLE
Countries not all showing

### ISSUE THREAD

**Issue by Danie10** [EliotBerriot/mnm#15]
Opening the list of country codes I don't see ZA for South Africa?

**Comment by EliotBerriot** [comment]
Do you mean the list of country codes available in the filter in [this](https://dashboards.mnm.social/dashboard/db/statuses?refresh=15m&orgId=1) dashboard, for example?

This is because it only lists country codes that actually have data (instances, users, statuses...). This means at the moment there is no Mastodon activity in South Africa, based on the instances list available at http://instances.mastodon.xyz/

**Comment by Danie10** [comment]
Yes that is correct. I see it does state the IP addresses are actually the locations of Instances, and not users at all. Strictly speaking, the data is quite correct. I suppose it was an incorrect assumption as we often think of user location. We'll probably never see actual user location as people are registering with Instances outside of their country in many cases.

**Comment by EliotBerriot** [comment]
There is indeed an ambiguity. We think "user location" while we only have "instance" location available.
