### ISSUE TITLE
Instance location map in case of missing data

### ISSUE THREAD

**Issue by jemus42** [EliotBerriot/mnm#3]
Example:
https://mnm.eliotberriot.com/dashboard/db/instance-detail?refresh=30m&orgId=1

The upper left map shows lon|lat 0|0: https://dump.jemu.name/2017-04-crll5z7ffu42qkw.png
Wich isn't clearly visible as "no location data available", so I propose that in cases where there's no reliable location data, the map element should be hidden, as it's basically just a generic map with no information on it at that point.

**Comment by EliotBerriot** [comment]
The map is always pointing to 0/0 by default, because it's not actually focusing on the given instance location (I have no way to do this in Grafana at the moment). For the same reason, I cannot hide a widget automatically if it has no data, it's not supported either by Grafana.

However, in the current case, there was, indeed, a location for the oulipo.social instance. It was just not visible because the default zoom level of the map was too important. I tweaked that and now, the default zoom level should make any instance location visible immediatly.

Thank you for reporting this, can you confirm this now works?
